[workspace]
members = ["secparser", "secparser_examples"]

[workspace.package]
version = "0.0.0"
edition = "2021"
description = "SEC Parser"
repository = "https://github.com/johnhuichen/secparser"
keywords = ["SEC"]
categories = ["finance", "command-line-utilities"]
license = "Apache-2.0"

[workspace.dependencies]
secparser = { path = "./secparser" }
