[workspace]
members = ["secparser", "secparser_examples"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
description = "SEC Parser"
repository = "https://github.com/johnhuichen/secparser"
keywords = ["SEC"]
categories = ["finance", "command-line-utilities"]
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.86"
derive_builder = "0.20.0"
secparser = { path = "./secparser" }
